[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "financial-fraud"
version = "0.1.0"
requires-python = ">=3.11"

dependencies = [
  "huggingface_hub>=1.2.3",
  "pandas>=2.3.3",
  "pyarrow>=22.0.0",
  "duckdb>=1.4.3",
  "redis>=7.1.0",
  "scikit-learn>=1.4",
  "lightgbm>=4.6.0",
  "xgboost>=3.1.2",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[project.optional-dependencies]
dev = [
  "jupyter",
  "ipykernel",
]